services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lead-conversation
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: